import * as cdk from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { Environment } from '@common/parameters/environments';
import { S3AmplifyStaticWebsiteStack } from 'lib/stacks/s3-amplify-static-website-stack';

const defaultEnv = {
  account: '123456789012',
  region: 'ap-northeast-1',
};

const projectName = 'example';
const envName: Environment = Environment.TEST;

describe('CDK Nag AwsSolutions Pack', () => {
  let app: cdk.App;
  let stack: S3AmplifyStaticWebsiteStack;

  beforeAll(() => {
    app = new cdk.App();

    stack = new S3AmplifyStaticWebsiteStack(app, `${projectName}-${envName}`, {
      project: projectName,
      environment: envName,
      isAutoDeleteObject: false,
      terminationProtection: false,
      env: defaultEnv,
    });

    applySuppressions(stack);

    cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
  });

  test('No unsuppressed Warnings', () => {
    const warnings = Annotations.fromStack(stack).findWarning(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*'),
    );
    if (warnings.length > 0) {
      console.log('\n=== CDK Nag Warnings ===');
      warnings.forEach((warning, index) => {
        console.log(`\nWarning ${index + 1}:`);
        console.log(`  Path: ${warning.id}`);
        console.log(`  Entry:`, JSON.stringify(warning.entry, null, 2));
      });
      console.log('======================\n');
    }
    expect(warnings).toHaveLength(0);
  });

  test('No unsuppressed Errors', () => {
    const errors = Annotations.fromStack(stack).findError(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*'),
    );
    if (errors.length > 0) {
      console.log('\n=== CDK Nag Errors ===');
      errors.forEach((error, index) => {
        console.log(`\nError ${index + 1}:`);
        console.log(`  Path: ${error.id}`);
        console.log(`  Entry:`, JSON.stringify(error.entry, null, 2));
      });
      console.log('======================\n');
    }
    expect(errors).toHaveLength(0);
  });

  test('Amplify App is defined', () => {
    expect(stack.amplifyApp).toBeDefined();
  });
});

function applySuppressions(stack: S3AmplifyStaticWebsiteStack): void {
  const stackName = stack.stackName;

  // The AwsCustomResource construct generates an auto-managed Lambda and IAM role.
  // The managed policy and wildcard S3 policy cannot be customized from user code.
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-IAM4',
        reason:
          'AWSLambdaBasicExecutionRole is an accepted baseline for the AwsCustomResource-generated Lambda in this sample.',
        appliesTo: [
          'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
        ],
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'Wildcard S3 actions (s3:GetObject*, s3:GetBucket*, s3:List*) are generated by CDK Asset\'s grantRead() and are scoped to the specific CDK bootstrap bucket and asset key. The amplify:StartDeployment wildcard resource is required because the Amplify app ID is a token at policy-attachment time.',
      },
      {
        id: 'AwsSolutions-L1',
        reason:
          'Lambda runtime for the AwsCustomResource handler is managed by CDK and is not directly configurable from user code.',
      },
    ],
    true,
  );

  console.log(`CDK Nag suppressions applied to stack: ${stackName}`);
}
