import * as cdk from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { AppStage } from '../lib/app-stage';
import { PipelineStack } from '../lib/pipeline-stack';

const env = { account: '123456789012', region: 'ap-northeast-1' };

describe('CDK Nag AwsSolutions', () => {
  const app = new cdk.App();
  const pipelineStack = new PipelineStack(app, 'Pipeline', { project: 'test', environment: 'test', isAutoDeleteObject: true, env });
  const helloStack = new AppStage(app, 'NagDev', { project: 'test', environment: 'test', stageName: 'Dev', env }).node.findChild('Hello') as cdk.Stack;

  // CDK Pipelines generates its IAM roles/policies and CodeBuild projects; these findings are inherent to the construct.
  NagSuppressions.addStackSuppressions(
    pipelineStack,
    [
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'CDK Pipelines generates wildcard grants it needs to work: artifact bucket objects, CloudWatch Logs streams, ' +
          'CodeBuild report groups, and sts:AssumeRole on the CDK bootstrap roles (cdk-*).',
      },
      {
        id: 'AwsSolutions-IAM4',
        reason: 'The default CodeBuild / CodePipeline role policies are generated by the CDK Pipelines construct.',
      },
      {
        id: 'AwsSolutions-CB4',
        reason: 'Build output is only the synthesized cloud assembly, stored in the SSE-S3 encrypted artifact bucket; a CMK is not required for this reference.',
      },
      {
        id: 'AwsSolutions-S1',
        reason: 'Server access logging for a short-lived pipeline artifact bucket adds a second bucket for no audit benefit here.',
      },
    ],
    true,
  );
  cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));

  test.each([
    ['Pipeline', pipelineStack],
    ['Hello', helloStack],
  ])('%s has no unsuppressed warnings or errors', (_name, stack) => {
    expect(Annotations.fromStack(stack).findWarning('*', Match.stringLikeRegexp('AwsSolutions-.*'))).toHaveLength(0);
    expect(Annotations.fromStack(stack).findError('*', Match.stringLikeRegexp('AwsSolutions-.*'))).toHaveLength(0);
  });
});
