import * as cdk from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { Environment } from '@common/parameters/environments';
import { params } from 'parameters/environments';
import '../parameters';

import { BaseStack } from 'lib/stacks/base-stack';
import { AppStack } from 'lib/stacks/app-stack';
import { FisStack } from 'lib/stacks/fis-stack';

const defaultEnv = {
    account: '123456789012',
    region: 'ap-northeast-1',
};

const projectName = 'fis-chaos-f';
const envName: Environment = Environment.TEST;

if (!params[envName]) {
    throw new Error(`No parameters found for environment: ${envName}`);
}
const envParams = params[envName]!;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeStacks(appId: string) {
    const app = new cdk.App();

    const baseStack = new BaseStack(app, `${appId}Base`, {
        project: projectName,
        environment: envName,
        env: defaultEnv,
        isAutoDeleteObject: true,
        terminationProtection: false,
    });

    const appStack = new AppStack(app, `${appId}App`, {
        project: projectName,
        environment: envName,
        env: defaultEnv,
        isAutoDeleteObject: true,
        terminationProtection: false,
        table: baseStack.table,
    });

    const fisStack = new FisStack(app, `${appId}Fis`, {
        project: projectName,
        environment: envName,
        env: defaultEnv,
        terminationProtection: false,
        reserveInventoryFn: appStack.reserveInventoryFn,
        processPaymentFn: appStack.processPaymentFn,
        confirmOrderFn: appStack.confirmOrderFn,
        stateMachine: appStack.stateMachine,
        alarmEmail: envParams.alarmEmail,
    });

    return { app, baseStack, appStack, fisStack };
}

// ---------------------------------------------------------------------------
// Suppression helper
// ---------------------------------------------------------------------------

function suppressBaseStack(stack: BaseStack): void {
    // PITR is intentionally disabled — this is a chaos-engineering demo table
    // that costs zero at rest. Point-in-time recovery adds cost with no benefit here.
    NagSuppressions.addResourceSuppressionsByPath(
        stack,
        `/${stack.stackName}/OrdersTable/Resource`,
        [
            {
                id: 'AwsSolutions-DDB3',
                reason:
                    'PITR is intentionally disabled for this PAY_PER_REQUEST chaos demo table. ' +
                    'The table is destroyed with the stack and never holds production data.',
            },
        ],
    );
}

function suppressAppStack(stack: AppStack): void {
    // Lambda functions: AWSLambdaBasicExecutionRole is an accepted baseline for sample functions.
    // AwsSolutions-L1 fires because cdk-nag may lag behind AWS runtime releases and not yet
    // recognise Python 3.13 as the latest runtime. Python 3.13 is the most recent Lambda Python
    // runtime at the time this workspace was authored.
    NagSuppressions.addStackSuppressions(
        stack,
        [
            {
                id: 'AwsSolutions-IAM4',
                reason:
                    'AWSLambdaBasicExecutionRole is an accepted baseline for Lambda functions in ' +
                    'this sample, and AWSXRayDaemonWriteAccess is required for X-Ray tracing.',
                appliesTo: [
                    'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
                    'Policy::arn:<AWS::Partition>:iam::aws:policy/AWSXRayDaemonWriteAccess',
                ],
            },
            {
                id: 'AwsSolutions-L1',
                reason:
                    'Python 3.13 is the latest available Lambda Python runtime. cdk-nag may not yet ' +
                    'recognise it as the latest due to release lag in the rule definitions.',
            },
        ],
        true,
    );

    // table.grantReadWriteData() generates a wildcard on index resources (table/*), and the
    // Step Functions state machine role needs InvokeFunction on multiple Lambda function
    // versions/aliases (a CDK-generated wildcard suffix), plus X-Ray and Logs delivery actions
    // that do not support resource-level restriction.
    NagSuppressions.addStackSuppressions(
        stack,
        [
            {
                id: 'AwsSolutions-IAM5',
                reason:
                    'Wildcard permissions are generated by table.grantReadWriteData() for index ' +
                    'sub-resources (table/*), by lambdaFunction.grantInvoke() used internally by ' +
                    'tasks.LambdaInvoke for the ":*" version/alias suffix, and by the CDK-managed ' +
                    'X-Ray / CloudWatch Logs delivery permissions required by the state machine, ' +
                    'none of which support further resource-level scoping.',
            },
        ],
        true,
    );
}

function suppressFisStack(stack: FisStack): void {
    // FIS log delivery requires a broad set of CloudWatch Logs management permissions;
    // there is no resource-scoped alternative for log delivery API actions.
    // The SNS alarm topic is an internal operational topic used only by CloudWatch alarm actions
    // (no external publishers). Enforcing SSL for publishers is out of scope here.
    NagSuppressions.addStackSuppressions(
        stack,
        [
            {
                id: 'AwsSolutions-IAM5',
                reason:
                    'FIS experiment logging to CloudWatch requires log delivery management actions ' +
                    '(CreateLogDelivery, ListLogDeliveries, etc.) which do not support resource-level ' +
                    'restrictions — wildcard is the only valid resource for these actions.',
            },
            {
                id: 'AwsSolutions-SNS3',
                reason:
                    'The FIS alarm topic is an internal operational topic whose only publisher is ' +
                    'the CloudWatch alarm action. No external publishers exist. ' +
                    'Enforcing SSL for publishers via an aws:SecureTransport policy is out of scope ' +
                    'for this chaos engineering reference pattern.',
            },
        ],
        true,
    );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('CDK Nag AwsSolutions — BaseStack', () => {
    let baseStack: BaseStack;

    beforeAll(() => {
        const { app, baseStack: bs } = makeStacks('NagBase');
        baseStack = bs;
        suppressBaseStack(baseStack);
        cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
    });

    test('No unsuppressed Warnings', () => {
        const warnings = Annotations.fromStack(baseStack).findWarning(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (warnings.length > 0) {
            console.log('\n=== CDK Nag Warnings (BaseStack) ===');
            warnings.forEach((w, i) =>
                console.log(`Warning ${i + 1}: ${w.id}\n${JSON.stringify(w.entry, null, 2)}`),
            );
        }
        expect(warnings).toHaveLength(0);
    });

    test('No unsuppressed Errors', () => {
        const errors = Annotations.fromStack(baseStack).findError(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (errors.length > 0) {
            console.log('\n=== CDK Nag Errors (BaseStack) ===');
            errors.forEach((e, i) =>
                console.log(`Error ${i + 1}: ${e.id}\n${JSON.stringify(e.entry, null, 2)}`),
            );
        }
        expect(errors).toHaveLength(0);
    });
});

describe('CDK Nag AwsSolutions — AppStack', () => {
    let appStack: AppStack;

    beforeAll(() => {
        const { app, appStack: as } = makeStacks('NagApp');
        appStack = as;
        suppressAppStack(appStack);
        cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
    });

    test('No unsuppressed Warnings', () => {
        const warnings = Annotations.fromStack(appStack).findWarning(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (warnings.length > 0) {
            console.log('\n=== CDK Nag Warnings (AppStack) ===');
            warnings.forEach((w, i) =>
                console.log(`Warning ${i + 1}: ${w.id}\n${JSON.stringify(w.entry, null, 2)}`),
            );
        }
        expect(warnings).toHaveLength(0);
    });

    test('No unsuppressed Errors', () => {
        const errors = Annotations.fromStack(appStack).findError(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (errors.length > 0) {
            console.log('\n=== CDK Nag Errors (AppStack) ===');
            errors.forEach((e, i) =>
                console.log(`Error ${i + 1}: ${e.id}\n${JSON.stringify(e.entry, null, 2)}`),
            );
        }
        expect(errors).toHaveLength(0);
    });
});

describe('CDK Nag AwsSolutions — FisStack', () => {
    let fisStack: FisStack;

    beforeAll(() => {
        const { app, fisStack: fs } = makeStacks('NagFis');
        fisStack = fs;
        suppressFisStack(fisStack);
        cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
    });

    test('No unsuppressed Warnings', () => {
        const warnings = Annotations.fromStack(fisStack).findWarning(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (warnings.length > 0) {
            console.log('\n=== CDK Nag Warnings (FisStack) ===');
            warnings.forEach((w, i) =>
                console.log(`Warning ${i + 1}: ${w.id}\n${JSON.stringify(w.entry, null, 2)}`),
            );
        }
        expect(warnings).toHaveLength(0);
    });

    test('No unsuppressed Errors', () => {
        const errors = Annotations.fromStack(fisStack).findError(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (errors.length > 0) {
            console.log('\n=== CDK Nag Errors (FisStack) ===');
            errors.forEach((e, i) =>
                console.log(`Error ${i + 1}: ${e.id}\n${JSON.stringify(e.entry, null, 2)}`),
            );
        }
        expect(errors).toHaveLength(0);
    });
});
