import * as cdk from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { Environment } from '@common/parameters/environments';
import { SecretsRotationAuroraStack } from 'lib/stacks/secrets-rotation-aurora-stack';
import { params } from 'parameters/environments';
import '../parameters';

const testEnv = { account: '123456789012', region: 'ap-northeast-1' };
const envName: Environment = Environment.TEST;
const envParams = params[envName];
if (!envParams) {
  throw new Error(`No parameters found for environment: ${envName}`);
}

describe('CDK Nag AwsSolutions Pack', () => {
  let stack: SecretsRotationAuroraStack;

  beforeAll(() => {
    const app = new cdk.App();
    stack = new SecretsRotationAuroraStack(app, 'ExampleSecretsRotationAurora', {
      project: 'example',
      environment: envName,
      isAutoDeleteObject: true,
      env: testEnv,
      params: envParams,
    });
    applySuppressions(stack);
    cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
  });

  test('no unsuppressed Warnings', () => {
    const warnings = Annotations.fromStack(stack).findWarning('*', Match.stringLikeRegexp('AwsSolutions-.*'));
    if (warnings.length > 0) console.log(JSON.stringify(warnings.map((w) => ({ id: w.id, entry: w.entry.data })), null, 2));
    expect(warnings).toHaveLength(0);
  });

  test('no unsuppressed Errors', () => {
    const errors = Annotations.fromStack(stack).findError('*', Match.stringLikeRegexp('AwsSolutions-.*'));
    if (errors.length > 0) console.log(JSON.stringify(errors.map((e) => ({ id: e.id, entry: e.entry.data })), null, 2));
    expect(errors).toHaveLength(0);
  });
});

/** Each suppression states why; only inherent-to-the-construct or environment-dependent findings are suppressed. */
function applySuppressions(stack: cdk.Stack): void {
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-RDS10',
        reason: 'Deletion protection follows the environment (isAutoDeleteObject): off in dev/test so the stack can be destroyed, on in production. The unit test asserts both.',
      },
      {
        id: 'CdkNagValidationFailure',
        reason: 'AwsSolutions-EC23 cannot evaluate the interface endpoint rule because its source is the VPC CIDR (a CloudFormation token); the rule allows only 443 from inside the VPC.',
      },
      {
        id: 'AwsSolutions-IAM4',
        reason: 'AWSLambdaBasicExecutionRole is the AWS-recommended logging policy; the VPC flow log and hosted rotation stacks use AWS-managed policies.',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason: 'The VPC flow-log role and the RDS Data API/secret grants are scoped to the cluster and secret ARNs; wildcards are the stream/log-stream suffixes generated by CDK helpers.',
      },
      {
        id: 'AwsSolutions-L1',
        reason: 'The hosted rotation functions and any library-generated helper functions are managed by AWS / aws-cdk-lib, not pinned by this stack.',
      },
      {
        id: 'AwsSolutions-RDS6',
        reason: 'IAM database authentication is enabled on the cluster; the secrets-based rotation path is the point of this reference.',
      },
    ],
    true,
  );
}
