import * as cdk from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { Environment } from '@common/parameters/environments';

import { TransferSftpCustomIdpStack } from 'lib/stacks/transfer-sftp-custom-idp-stack';
import { EnvParams, params } from "parameters/environments";
import '../parameters';

const defaultEnv = {
    account: '123456789012',
    region: 'ap-northeast-1',
};

const projectName = "example";
const envName: Environment = Environment.TEST;
if (!params[envName]) {
  throw new Error(`No parameters found for environment: ${envName}`);
}
const baseParams = params[envName] as EnvParams;

const lifecycles: EnvParams['serverLifecycle'][] = [
  { mode: 'always' },
  { mode: 'manual' },
  {
    mode: 'scheduled',
    startExpression: 'cron(0 8 ? * MON-FRI *)',
    stopExpression: 'cron(0 20 ? * MON-FRI *)',
    timezone: 'Asia/Tokyo',
  },
];

describe.each(lifecycles)('CDK Nag AwsSolutions Pack ($mode)', (lifecycle) => {
  let stack: TransferSftpCustomIdpStack;

  beforeAll(() => {
    const app = new cdk.App();
    stack = new TransferSftpCustomIdpStack(app, `${projectName}-${envName}`, {
      project: projectName,
      environment: envName,
      isAutoDeleteObject: true,
      env: defaultEnv,
      envParams: { ...baseParams, serverLifecycle: lifecycle },
    });

    // Apply suppressions (must be applied before adding Aspects)
    applySuppressions(stack);
    cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
  });

  test('No unsuppressed Warnings', () => {
    const warnings = Annotations.fromStack(stack).findWarning('*', Match.stringLikeRegexp('AwsSolutions-.*'));
    if (warnings.length > 0) {
      console.log(JSON.stringify(warnings.map((w) => ({ path: w.id, msg: w.entry.data })), null, 2));
    }
    expect(warnings).toHaveLength(0);
  });

  test('No unsuppressed Errors', () => {
    const errors = Annotations.fromStack(stack).findError('*', Match.stringLikeRegexp('AwsSolutions-.*'));
    if (errors.length > 0) {
      console.log(JSON.stringify(errors.map((e) => ({ path: e.id, msg: e.entry.data })), null, 2));
    }
    expect(errors).toHaveLength(0);
  });
});

/**
 * Apply CDK Nag suppressions to the stack. Each one is scoped to a resource path and has a specific reason.
 * @param stack The stack under test
 */
function applySuppressions(stack: TransferSftpCustomIdpStack): void {
  const prefix = `/${stack.stackName}`;

  NagSuppressions.addStackSuppressions(stack, [
    {
      id: 'AwsSolutions-S1',
      reason: 'The bucket is a verification SFTP data bucket; transfer activity is audited through Transfer Family structured logs and CloudTrail data events can be enabled per environment.',
    },
  ]);

  const suppressIfExists = (path: string, suppressions: Parameters<typeof NagSuppressions.addResourceSuppressionsByPath>[2], applyToChildren = false): void => {
    if (stack.node.tryFindChild(path.split('/')[0])) {
      NagSuppressions.addResourceSuppressionsByPath(stack, `${prefix}/${path}`, suppressions, applyToChildren);
    }
  };

  suppressIfExists('TransferAccessRole/DefaultPolicy/Resource', [{
    id: 'AwsSolutions-IAM5',
    reason: 'Object-level wildcard on the SFTP bucket is intentional. The custom IdP Lambda returns a per-user session policy that narrows access to the user home prefix.',
  }]);
  suppressIfExists('TransferLoggingRole/DefaultPolicy/Resource', [{
    id: 'AwsSolutions-IAM5',
    reason: 'Log stream names under the dedicated Transfer log group are generated by the service.',
  }]);
  suppressIfExists('IdpFunction/ServiceRole/Resource', [{
    id: 'AwsSolutions-IAM4',
    reason: 'AWSLambdaBasicExecutionRole is the standard managed policy for Lambda log delivery.',
    appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
  }]);
  suppressIfExists('UserAdminPolicy/Resource', [{
    id: 'AwsSolutions-IAM5',
    reason: 'Only the user table ARN is referenced; the wildcard suffix covers its indexes.',
  }], true);

  // on-demand server controller
  suppressIfExists('ServerController/ServiceRole/Resource', [{
    id: 'AwsSolutions-IAM4',
    reason: 'AWSLambdaBasicExecutionRole is the standard managed policy for Lambda log delivery.',
    appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
  }]);
  suppressIfExists('ServerController/ServiceRole/DefaultPolicy/Resource', [{
    id: 'AwsSolutions-IAM5',
    reason: 'The server ID does not exist at deploy time. CreateServer / ListServers and the CloudWatch Logs delivery actions that Transfer Family requires for structured logging do not support resource-level permissions; Delete/Describe are limited by a stack tag condition; alarm ARNs are limited to the stack prefix.',
  }]);
}
