import * as cdk from 'aws-cdk-lib';
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { AwsSolutionsChecks, NagSuppressions } from 'cdk-nag';
import { Environment } from '@common/parameters/environments';
import { EventbridgeCustomBusStack } from 'lib/stacks/eventbridge-custom-bus-stack';
import { params } from 'parameters/environments';
import '../parameters';

const testEnv = { account: '123456789012', region: 'ap-northeast-1' };
const envName: Environment = Environment.TEST;
const envParams = params[envName];
if (!envParams) {
  throw new Error(`No parameters found for environment: ${envName}`);
}

describe('CDK Nag AwsSolutions Pack', () => {
  let stack: EventbridgeCustomBusStack;

  beforeAll(() => {
    const app = new cdk.App();
    stack = new EventbridgeCustomBusStack(app, 'ExampleEventbridgeCustomBus', {
      project: 'example',
      environment: envName,
      isAutoDeleteObject: true,
      env: testEnv,
      params: envParams,
    });
    applySuppressions(stack);
    cdk.Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }));
  });

  test('no unsuppressed Warnings', () => {
    const warnings = Annotations.fromStack(stack).findWarning('*', Match.stringLikeRegexp('AwsSolutions-.*'));
    if (warnings.length > 0) console.log(JSON.stringify(warnings.map((w) => ({ id: w.id, entry: w.entry.data })), null, 2));
    expect(warnings).toHaveLength(0);
  });

  test('no unsuppressed Errors', () => {
    const errors = Annotations.fromStack(stack).findError('*', Match.stringLikeRegexp('AwsSolutions-.*'));
    if (errors.length > 0) console.log(JSON.stringify(errors.map((e) => ({ id: e.id, entry: e.entry.data })), null, 2));
    expect(errors).toHaveLength(0);
  });
});

/** Each suppression states why; only inherent-to-the-construct or costed-feature findings are suppressed. */
function applySuppressions(stack: cdk.Stack): void {
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-IAM4',
        reason: 'AWSLambdaBasicExecutionRole is the AWS-recommended logging policy; the CloudWatch Logs target helper also uses managed policies.',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason: 'The CloudWatch Logs target helper generates a log-group-scoped policy with a stream wildcard and a custom resource that creates the log resource policy.',
      },
      {
        id: 'AwsSolutions-L1',
        reason: 'The log-resource-policy custom resource Lambda is generated by the CDK library and its runtime is managed by aws-cdk-lib.',
      },
      {
        id: 'AwsSolutions-SQS3',
        reason: 'The target DLQ is itself the dead-letter destination; the two work queues are terminal targets whose failed deliveries go to that DLQ.',
      },
    ],
    true,
  );
}
